spring.application.name=firstmodule

# database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/firstmodule
spring.datasource.username=postgres
spring.datasource.password=postgres

# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
